### ISSUE TITLE
Always getting these in combat.

### ISSUE THREAD

**Issue by Kkthnx** [ElvUI/ElvUI#1]
![wowscrnshot_052015_155707](https://cloud.githubusercontent.com/assets/1692977/7735116/12f2a520-ff09-11e4-89c9-e7e87bd785b0.jpg)

**Comment by Bunny67** [comment]
It should be corrected

**Comment by Kkthnx** [comment]
Thanks! Will report anything else I find keep up the hard-work! Long live ElvUI on 3.3.5!

**Comment by Bunny67** [comment]
:)
