### ISSUE TITLE
RightClick SelfCast

### ISSUE THREAD

**Issue by lierox90** [ElvUI/ElvUI#10]
Idk if it is really issue, but there is missing rightclick self cast option for bars, there is plugin for it however it doesnt seem to work with yours version of ElvUI, it would be really awesome if it was implemented into addon :)

**Comment by Bunny67** [comment]
Ru: Если речь идет про аддон, то можно ссылку на него

Google translete: If it is about the addon, you can link to it

**Comment by lierox90** [comment]
http://www.tukui.org/addons/index.php?act=view&id=185 or
http://www.wowinterface.com/downloads/info21076-ElvUIright-clicktoself-cast.html

**Comment by Bunny67** [comment]
ElvUI_Bar1:SetAttribute("unit2", "player"); 
ElvUI_Bar2:SetAttribute("unit2", "player"); 
ElvUI_Bar3:SetAttribute("unit2", "player"); 
ElvUI_Bar4:SetAttribute("unit2", "player"); 
ElvUI_Bar5:SetAttribute("unit2", "player");

**Comment by lierox90** [comment]
what should i do with it ?

**Comment by Bunny67** [comment]
Add or create a new addon and add this code

**Comment by Bunny67** [comment]
or https://github.com/ElvUI/ElvUI_RightClick

**Comment by lierox90** [comment]
Sry it took so long it works, thanks :+1:  :D
