### ISSUE TITLE
[Request] ElvUI ExtraActionBars

### ISSUE THREAD

**Issue by Lexblack** [ElvUI/ElvUI#100]
I know that this is the wrong section to post this since is not an issue of the actual add-on but i don't know where else to post it.

ElvUI has only 5 Action Bars and some users need more like me.
This addon here adds 4 more action bars, so my request is can you port it so it can work with your version of ElvUI?
http://wow.curseforge.com/addons/elvui-oneextraactionbar/

**Comment by Bunny67** [comment]
Not supported

**Comment by Lexblack** [comment]
I see, thanks anyways.

**Comment by crumdidlyumshis** [comment]
Man I wish this could be ported :( My hunter has so many spells its insane!

**Comment by Bunny67** [comment]
LibActionButton-1.0 is unfortunately impossible to port to 3.3.5
