### ISSUE TITLE
Class Colors not working for Priest

### ISSUE THREAD

**Issue by Dissectional** [ElvUI/ElvUI#103]
Hi, last night I discovered the "Class Colors" feature is fully functional on Priests.
I tested on two servers, with 3 different Priests, all using the same profile.

I found that logging on to a Priest, the Player Frame would change to white but DataText, Chat Titles and Minimap Text would remain the color of whichever class had previously been logged on, provided that all characters are using the same profile.

It seems [this update](https://github.com/ElvUI/ElvUI/commit/f5deb94f19347afd9beebf9e150b99888810acfc) changed a lot of code to do with Class colors and makes specific changes to Priests so I suspect this did something to break it, I am not proficient enough at reading LUA to understand exactly what was changed here unfortunately.

I understand you don't speak English so hopefully Google Translate doesn't have too much trouble with this.

Thanks,
Dissy

**Comment by Bunny67** [comment]
fixed

**Comment by Dissectional** [comment]
Hi Bunny,
Thank you so much, I have just tested and working as expected.

Thanks,
Dissy
