### ISSUE TITLE
target unitframe format text values aren't always correct

### ISSUE THREAD

**Issue by credomane** [ElvUI/ElvUI#106]
My target unitframe has these text format values.

```
HEALTH = [healthcolor][health:current-percent]
POWER = [powercolor][power:current]
NAME = [namecolor][name:medium] [difficultycolor][level] [shortclassification]
```

When selecting a player values seem to be entirely correct. If selecting a NPC then the POWER and NAME text are incorrect. NAME becomes entirely blank. POWER takes the value that was supposed to be in NAME while the real value for POWER is no where to be seen.

```
[smartlevel] seems to be random on when it shows the level or perhaps I don't understand the rules behind it? NPCs seem to always have the right data but players are nearly always blank or wrong.
```

I'm poking about the code to see if I can figure anything out.

**Comment by credomane** [comment]
I played around with it some more before I went to bed last night. Whatever the issue is it isn't the [smart_tags] themselves. I can set the values to a pure plain text value and the issue still occurs. I'll get some screen shots when I get home from work in a few more hours. So you can see what is going on and perhaps have an idea.

I'll also grab the commit that came out an hour or so ago and see if perhaps that solves it!

**Comment by credomane** [comment]
The latest master still does it.
here is a cropped screenie. http://imgur.com/NXbRz4I

The left half is the "Player Frame" I left it in the screenshot just because. On the right half is the "Target Frame" which exhibits my problem. Bottom right is how the target frame is always supposed to be and how it looks only when selecting a player; be it myself, a party member, guild member, horde or alliance. If I select a NPC then the target frame looks as it does in the top right which is wrong.

As a test I made custom texts "health2", "power2", "name2" and they seem to be behaving correctly.

**Comment by Bunny67** [comment]
if I understand it /ec UnitFrames - Target Frame - Text Toggle On NPC

**Comment by credomane** [comment]
....That was exactly it. I saw that option but left it alone because I didn't know what it did. Had I bothered to read the help text for it then I would have saved you some time having to deal with a guy that can't read help text.

Sorry about that; Closing the ticket.
