### ISSUE TITLE
Pet bar buttons disappear

### ISSUE THREAD

**Issue by UntilSunrise** [ElvUI/ElvUI#107]
I'm a warlock. If I have to reload the UI and summoned a pet, on reload the buttons on the pet bar disappear and i have to resummon the pet

EDIT: nvm seems to be a server Problem. Disabled ElvUI doesnt fix the problem

**Comment by Bunny67** [comment]
This is a problem server. On the same server is not shown, and the other all right.

Ru: Это проблема сервера. На одном сервере не показывается, а на другом все нормально.

**Comment by crumdidlyumshis** [comment]
Yeah this bugged the shit out of me for a while until I realized that it was a server side issue. On the Warmane server Lordaeron, it works as intended.
