### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by LiNK2088** [ElvUI/ElvUI#11]
The tooltip shows about 30 pixels above the tooltip anchor, making it impossible to put the tooltip on the bottom of the screen.
(this is with the "cursor anchor" option turned off)

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI/commit/fd2bb5ef3f63aad620a046888b630a40bfb27377 ?

**Comment by LiNK2088** [comment]
That put it right above the anchor.
I did some testing and to make it perfect it has to be like this:

		local point = E:GetScreenQuadrant(TooltipMover)
		if point == "TOPLEFT" then
			tt:SetPoint("TOPLEFT", TooltipMover, "BOTTOMLEFT", 1, -4)
		elseif point == "TOPRIGHT" then
			tt:SetPoint("TOPRIGHT", TooltipMover, "BOTTOMRIGHT", -1, -4)
		elseif point == "BOTTOMLEFT" or point == "LEFT" then
			tt:SetPoint("BOTTOMLEFT", TooltipMover, "TOPLEFT", 0, -14)
		else
			tt:SetPoint("BOTTOMRIGHT", TooltipMover, "TOPRIGHT", 0, -14)
		end

note: I only tested and modified the bottom anchors, the top is not modified

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI/commit/b619b31a1b6bbf7d94df40cf2b7dc8b94b9ad163 so like better

**Comment by LiNK2088** [comment]
That also works :D ty
