### ISSUE TITLE
/elvui or ElvUI Config Button - Broken

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#111]
The slash command appears to be broken and the button.

**Comment by Bunny67** [comment]
Game settings did not open?

**Comment by crumdidlyumshis** [comment]
Yeah, it did not open. I reverted to using ElvUI 5.21 and it works fine. All the issues I posted happened after you released the latest update.

**Comment by Bunny67** [comment]
Try to update, enable the display of errors. At the entrance to the world of print /reload (display error, if any)

**Comment by crumdidlyumshis** [comment]
This works now after the recent update. Not sure what happened.
