### ISSUE TITLE
Latest Update - Action Bar - Broken

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#112]
![wowscrnshot_012016_210607](https://cloud.githubusercontent.com/assets/7307335/12470468/1f377a28-bfba-11e5-8cce-01af60b8bbdc.jpg)

**Comment by Bunny67** [comment]
Strangely enough, as they do not change except for renaming the fixation point

**Comment by Bunny67** [comment]
Try to reset the position of the bar2

**Comment by crumdidlyumshis** [comment]
I just moved the bar down. So far it works.
