### ISSUE TITLE
Vehicle Bar Combo Points

### ISSUE THREAD

**Issue by SRX1994** [ElvUI/ElvUI#113]
Hey,
Is it possible to show the Combopoints for Vehicle fights like Malygos?
I tried everything, cant seem to sort it out.

Thanks in advance! :)

**Comment by Bunny67** [comment]
Combopoints disabled by default, you may not have included them

**Comment by SRX1994** [comment]
how I can i add them?

**Comment by Bunny67** [comment]
Check
