### ISSUE TITLE
Power Infusion

### ISSUE THREAD

**Issue by SRX1994** [ElvUI/ElvUI#114]
Hey,
Is there any way to Add "Power Infusion" to my Buffbar? like above my Playerframe where I can see for example Trinket On-Use, Arcane Power etc.
I would love to see Power Infusion if a Priest gives me his CD.

I tried everything and I have like changed and added a lot of stuff for myself but this one is like not working.

Thanks for help in advance

**Comment by Nzith** [comment]
![wowscrnshot_012516_161753](https://cloud.githubusercontent.com/assets/16617127/12553338/8b0a6bd4-c37f-11e5-936f-d56800205dc0.jpg)

Add the spell name here.

**Comment by SRX1994** [comment]
I tried this multiple times and finally it worked :+1: weird.
Thanks for the help and sorry for the "Bugreport"
