### ISSUE TITLE
main tank & main assist frame

### ISSUE THREAD

**Issue by Tiny6** [ElvUI/ElvUI#115]
Very nice and awesome UI
i've been using for a long time!

start play Hpaly recently, and found out there's no debuff, buff and indicator shown on the main tank and assist frame.
is it possible to make it works like raid frame?

**Comment by Bunny67** [comment]
added

**Comment by Tiny6** [comment]
Thanks!!! the indicator works.
but the debuff like curse or disease etc. didn't show.
XD it would be perfect if can add them up.

Many thanks again!
