### ISSUE TITLE
Map Position Problem

### ISSUE THREAD

**Issue by Nzith** [ElvUI/ElvUI#117]
After your last update there is a problem with the map position.

This is how it was before
![wowscrnshot_012516_161753](https://cloud.githubusercontent.com/assets/16617127/12604422/1f56e7f0-c4c4-11e5-91a0-1d11bd17fe9a.jpg)

and this is how it is after the update
![wowscrnshot_012716_015833](https://cloud.githubusercontent.com/assets/16617127/12604429/2ee5515c-c4c4-11e5-8b20-60f394ed0cb2.jpg)

**Comment by xeek** [comment]
I have the same issue with the Map and I am unable to put it in the old Position
Also the Stance bar was in a different Position and when trying to change the position via coordinates  the stance bar reset all the time, I was able to move it with my mouse tho.

**Comment by Bunny67** [comment]
fixed
