### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by lierox90** [ElvUI/ElvUI#12]
First of all a noticed that the "Tracking" minimap button is quite bugged, it doesnt display tracking, like its alpha = 0, its placed in very strange spot (its unmovable), also other "build in" minimap buttons like pvp, rdf, difficulti marker for dungs seems to be somehow bugged, it would be awesome if minimap could be fixed a little bit, heres a pic of what im talking about : 
![image](https://cloud.githubusercontent.com/assets/4543689/9155602/08c2efb2-3ebd-11e5-8e02-870184f8f446.png)

Its more of a request, i remember that in original ElvUI there as special bar for all addons minimap buttons, it would be really awesome if it were to be added in future. :)

**Comment by lierox90** [comment]
Issue wasnt solved, why was it closed ?

**Comment by Bunny67** [comment]
When you move an icon is a circle, like the way it should be.
A special bar has a separate addon for ElvUI for this version is not supported.

**Comment by Bunny67** [comment]
Perhaps I'm not quite correctly understood the essence of the bug, because my language is Russian.
I translate using Google

**Comment by lierox90** [comment]
ok i just downloaded SwingBar but it doesnt do a thing, it just shows in plugins tab and nothing new appears

**Comment by lierox90** [comment]
![image](https://cloud.githubusercontent.com/assets/4543689/10228927/b2492dee-6875-11e5-9621-dd51a837690d.png)

**Comment by Bunny67** [comment]
Default is off

**Comment by lierox90** [comment]
so how should i turn it on?

**Comment by Bunny67** [comment]
UnitFrames/Player Frame/Select SwingBar in DropDown

**Comment by Bunny67** [comment]
Updated ElvUI MiniMapTrakking may disappear

**Comment by lierox90** [comment]
ok i turned on swingbar but this is not what i meant, in original addon under minimap there is bar with all addons listed by icon

**Comment by Bunny67** [comment]
https://github.com/ElvUI/SquareMinimapButtons support, It is?

**Comment by lierox90** [comment]
![image](https://cloud.githubusercontent.com/assets/4543689/10234497/30f7aaa2-6895-11e5-87dd-bd27b9ba8de6.png)]
Yes its exacly what i wanted, only minor addition would be awesome, if you could add to the bar LFG and PVP queue to the bar that would be freaking awesome.

Out of Curiousity what will Elv Bunny addon will do ?

**Comment by lierox90** [comment]
Ok, 1 more thing. Tracking button could change icon to the tracking that is turned on, now it jsut keeps on looking glass.
