### ISSUE TITLE
Guild Window - Up Down Buttons

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#123]
Not sure exactly, but I think those two buttons are missing their skins.

Close if I am incorrect.

![2016-02-01_10-16-37](https://cloud.githubusercontent.com/assets/7307335/12723021/2bdef76c-c8cd-11e5-8d8f-0e06674afc39.png)

**Comment by Bunny67** [comment]
check

**Comment by crumdidlyumshis** [comment]
Works! Thank you!
