### ISSUE TITLE
Power Bar and unitframe sized changed with last update

### ISSUE THREAD

**Issue by xeek** [ElvUI/ElvUI#124]
http://i.imgur.com/QRmrX65.png

as you can see in the Screenshot the size of the power bar on focus and target of target frame doesn't match the size of my unit frames anymore.

Also the Buffs/Debuffs aren't the same size as my unit frames anymore, it looks like the player and target unitframes are just 1px smaller than before?
I mean this second issue is easily fixable by myself, but maybe its a bug.

**Comment by Bunny67** [comment]
check

**Comment by xeek** [comment]
it's fixed, thank you
