### ISSUE TITLE
Latest Update - Action Bars

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#128]
![wowscrnshot_022416_141749](https://cloud.githubusercontent.com/assets/7307335/13299613/7d1d2c98-db01-11e5-9e58-4b29de06e551.jpg)

I cannot get the bars to work.

**Temporarily reverting to previous ElvUI.

**Comment by Bunny67** [comment]
check

**Comment by crumdidlyumshis** [comment]
Fixed! Thank you!
