### ISSUE TITLE
ElvUI - 95% Broken - Fresh Install

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#129]
So I decided to do a complete fresh install of ElvUI with ElvUI_Config.... turns out that its really broken after last update. Check this out.

I deleted my WTF, this is from the login, fresh and clean.

I think you may have missed a few files xD haha. 

![wowscrnshot_022516_130550](https://cloud.githubusercontent.com/assets/7307335/13330928/c65f5a10-dbc0-11e5-9427-917d98d6d956.jpg)

**Comment by Bunny67** [comment]
fixed

**Comment by crumdidlyumshis** [comment]
Fixed! Thank you!
