### ISSUE TITLE
I think this is an addon clash, I don't know which one though

### ISSUE THREAD

**Issue by Harris247** [ElvUI/ElvUI#13]
![error](https://cloud.githubusercontent.com/assets/13817889/9292787/77c944ce-4403-11e5-953e-3633d76e944c.JPG)

I included the error message above, it happens every time I zone in anywhere, teleport or reload.

**Comment by Harris247** [comment]
Sorry I should include my enabled addons:

**Comment by Bunny67** [comment]
This ElvUI client 3.3.5a, you have 6.2 as I understand

**Comment by Harris247** [comment]
Yes, is my ElvUI outdated?
