### ISSUE TITLE
Battlefield Minimap - OpacityFrameSlider

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#131]
![wowscrnshot_022416_235333](https://cloud.githubusercontent.com/assets/7307335/13363138/8f30b408-dc8d-11e5-9f6e-af58f91f83f5.jpg)

**Comment by Bunny67** [comment]
fixed

**Comment by crumdidlyumshis** [comment]
cool! :+1:  :)
