### ISSUE TITLE
Unitframes > Portrait > Options

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#133]
Would it be possible to add these options to the portrait?

Current

![wowscrnshot_030616_183342](https://cloud.githubusercontent.com/assets/7307335/13558442/77b981d0-e3ca-11e5-9751-fbd01ce24474.jpg)

Retail

![wowscrnshot_030616_183451](https://cloud.githubusercontent.com/assets/7307335/13558438/66e15e96-e3ca-11e5-9bef-2cf367851b12.jpg)

**Comment by Bunny67** [comment]
Do not allow API
