### ISSUE TITLE
Portrait

### ISSUE THREAD

**Issue by alejhg89** [ElvUI/ElvUI#134]
In previous versions you could separate the portrait of the rest, in the last vercion you can not ...

**Comment by Bunny67** [comment]
Google Translete:
This feature has been removed to ElvUI was similar to the original
Now she is in https://github.com/ElvUI/ElvUI_Bunny

Ru:
Эта функция была удалена чтобы ElvUI был похожим на оригинальный
Теперь она находится в https://github.com/ElvUI/ElvUI_Bunny

**Comment by alejhg89** [comment]
ok, thanks
