### ISSUE TITLE
nameplates

### ISSUE THREAD

**Issue by alejhg89** [ElvUI/ElvUI#135]
Cuando desactivo los beneficios o perjuicios en las nameplates, automaticamente se me desactian las nameplates...

When I turn on the benefits or harm nameplates, I automatically turn off the nameplates ...

**Comment by alejhg89** [comment]
sorry, 
When I turn off the benefits or harm nameplates, I automatically turn off the nameplates ...

**Comment by Bunny67** [comment]
I do not understand written text :( Google It translates not clear :(

**Comment by Bunny67** [comment]
Usted puede tomar una captura de pantalla?

**Comment by crumdidlyumshis** [comment]
Por favor, tome una captura de pantalla del problema que está teniendo .

**Comment by alejhg89** [comment]
when I turn off the buff and debuff on nameplates, nameplates are turned off

**Comment by alejhg89** [comment]
I use plate buff

**Comment by alejhg89** [comment]
.

**Comment by Bunny67** [comment]
buff and debuff on nameplates can not be disabled

**Comment by alejhg89** [comment]
![wowscrnshot_030916_182854](https://cloud.githubusercontent.com/assets/14810165/13677610/41cebdcc-e6b0-11e5-81ca-1f24e8196258.jpg)

**Comment by alejhg89** [comment]
The option is, but doing so disables the addon

**Comment by Bunny67** [comment]
it disables nameplates

**Comment by alejhg89** [comment]
only when I turn off the buff and debuff, but I want to use nameplates without buff and debuff

**Comment by alejhg89** [comment]
![wowscrnshot_030716_172651](https://cloud.githubusercontent.com/assets/14810165/13678395/fc9969e2-e6b3-11e5-84f6-f4647504285a.jpg)
here with platebuff and  nameplate elvui, but I just want to have those platebuff

**Comment by Bunny67** [comment]
they can not be disabled, and it will be difficult to add a trip to the settings

**Comment by alejhg89** [comment]
thank you very much, grateful for your help

**Comment by Bunny67** [comment]
Now you can disable them
