### ISSUE TITLE
Links arent clickable

### ISSUE THREAD

**Issue by ukkoclap** [ElvUI/ElvUI#137]
Links aren't clickable in chat where you can copy/paste the link thats marked I remember it did in MoP.

**Comment by TheBabkin** [comment]
I confirme that, but I found the way to do it. Just press Enter, then hold shift and left click on link, you can copy then.

**Comment by ukkoclap** [comment]
Thanks for the tip

**Comment by crumdidlyumshis** [comment]
Duplicate post: https://github.com/ElvUI/ElvUI/issues/54

Bunny67 will get around to it sometime :)

**Comment by Bunny67** [comment]
check

**Comment by Lexblack** [comment]
It works now, you can close this.
