### ISSUE TITLE
Target Frame - Name Position

### ISSUE THREAD

**Issue by Alx1502** [ElvUI/ElvUI#139]
Target Frame - Name Position is broken. 
![wowscrnshot_032316_224128](https://cloud.githubusercontent.com/assets/16160069/14000285/4a00a8ea-f149-11e5-9a7d-4d52dc29b887.jpg)

**Comment by Alx1502** [comment]
Player Name broken too. Not show at all.

**Comment by Bunny67** [comment]
uncheck Text Toggle On NPC

**Comment by Alx1502** [comment]
Yep, that made it work. thanks!
