### ISSUE TITLE
Boss Frame Not Showing

### ISSUE THREAD

**Issue by Trden** [ElvUI/ElvUI#14]
Boss Frame does not work.

**Comment by Bunny67** [comment]
What the boss is not working?

**Comment by Trden** [comment]
On all bosses, the boss frame that shows the boss' HP is not displaying.

**Comment by Trden** [comment]
Босс Рамка ? 
Translated from Google Translate.

**Comment by Bunny67** [comment]
They appear only on some bosses in Icecrown Citadel

Ru: Они должны появляться только на некоторых боссах в ЦЛК

**Comment by Trden** [comment]
Yes, the problem is they do not appear even on bosses in Icecrown Citadel for some reason.

**Comment by Bunny67** [comment]
You should appear at the Blood Princes Council and Gunship Battle

**Comment by Trden** [comment]
What about all the other fights tho..?

**Comment by Bunny67** [comment]
![wowscrnshot_082015_202458](https://cloud.githubusercontent.com/assets/5816685/9390453/dfc32594-4779-11e5-8451-754ea106eb63.jpg)

**Comment by Bunny67** [comment]
On Gunship Batlle should also work

**Comment by Trden** [comment]
Okay, but how about on other bosses? Is there anyway to make it work?

**Comment by Trden** [comment]
Also, on Gunship Battle, it doesn't work for English Client. Please look into this problem if you can.

**Comment by Bunny67** [comment]
On Gunship Batlle could not work because of a server.
