### ISSUE TITLE
Latest Update - Fresh Install - Errors

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#141]
https://github.com/ElvUI/ElvUI/commit/d9547aa2fde899031e1c574a68777acbabeeb6c6

![world of warcraft 3_24_2016 11_55_38 am](https://cloud.githubusercontent.com/assets/7307335/14024528/8794911c-f1b7-11e5-93be-3b39a17cc64c.png)

Deleted WTF/Interface - Reinstalled ElvUI

I logged into my druid with a clean install. These are the errors that popped up immediately.

1/5: http://pastebin.com/raw/qss8YXPB

2/5: http://pastebin.com/raw/sxGMHV0D

3/5: http://pastebin.com/raw/q4Bpuubs

4/5: http://pastebin.com/raw/ZzDcsKbk

5/5: http://pastebin.com/raw/74SQkjZq

**Comment by Bunny67** [comment]
Problem in ElvUI_Bunny

**Comment by Bunny67** [comment]
Fixed in ElvUI_Bunny

**Comment by crumdidlyumshis** [comment]
Confirmed fix! Thank you!
