### ISSUE TITLE
Combo Points

### ISSUE THREAD

**Issue by lierox90** [ElvUI/ElvUI#15]
There is no way to display Combo Points under Target Frame just like its explained here, and just as it is in Original addon 

https://www.reddit.com/r/wow/comments/32vjlm/how_to_display_combo_points_on_player_frame_in/

**Comment by Bunny67** [comment]
By default they are turned off. UnitFrames>Target Frame>Combobar>Enable

**Comment by lierox90** [comment]
There is no Combobar option in Target Frame

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI/blob/master/ElvUI_Config/unitframes.lua#L2178 It must be. Take a screenshot of the drop-down menu in the Target Frame
