### ISSUE TITLE
Buff Indicator color inverted

### ISSUE THREAD

**Issue by zelda1220** [ElvUI/ElvUI#152]
http://imgur.com/z3ygOR5

Look at the raid group and look at my name's buff indicator.

The remaining time of the buff should be highlighted with the color, but at this moment, it is working the other day. The remaining time is colored black.

**Comment by zelda1220** [comment]
Issue continues. Please look into this problem.

**Comment by Bunny67** [comment]
I did not understand what the problem :(

**Comment by Kkthnx** [comment]
@zelda1220 In your screenshot, there is no cooldown or remaining time that is black like you spoke of. Can you please explain the issue in more detail and make sure the problem is only happening when ElvUI for 3.3.5 is installed. Also, be certain you are updated to the latest version.

**Comment by zelda1220** [comment]
If you've played healer, you would understand. Look at the raid grid supported by ElvUI and look at my name (Silentwords). The red square on the top left indicates the remaining time of Weakened Soul. The yellow square on the bottom right indicates the remaining time of PW:S. Okay, now, look at my buff. PW:S is on 27 seconds. (30 seconds at start). But, if you look at the square on the raid grid, the REMAINING TIME OF THE BUFF is GREYED OUT (BLACKED OUT). The REMAINING TIME SHOULD BE YELLOW, but currently, it is the other way around. I read the patch-note about "reverse" on buff indicator, but I couldn't find the "Reverse" function at all at anywhere.

**Comment by Lexblack** [comment]
I don't think Reverse highlight options has anything to do with the raid frames.
![wowscrnshot_050916_044628](https://cloud.githubusercontent.com/assets/16202997/15101862/4588cc26-15a1-11e6-92b4-b217ba6fdcf1.jpg)

The Options for the buff/debuff indicators are here:
![wowscrnshot_050916_045053](https://cloud.githubusercontent.com/assets/16202997/15101897/b8b2f550-15a1-11e6-88eb-dfe982d95662.jpg)

**Comment by zelda1220** [comment]
I see. It was working fine until this "Reverse Reminder time" update. I got the newest update (updated 8 hours ago), but problem still persists. I may add another screenshot to help you guys understand a bit more if still not sure what's wrong.

You can go on your healer, get on raid group, cast a spell on yourself, look at your raid grid, and you will notice.. The REMAINING TIME should be colored, not greyed out, which is the case right now.

**Comment by Lexblack** [comment]
![wowscrnshot_050916_151944](https://cloud.githubusercontent.com/assets/16202997/15113013/7174adc4-15fa-11e6-80f9-acce66dfcd0b.jpg)
You mean that the colors on the raid frame should be the other way around? I never really noticed that cause i use textured icons instead of colored ones.

**Comment by zelda1220** [comment]
@Lexblack  YES! YES! Finally, someone got what I was talking about (cry)

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI/commit/bc4fcef284d48008af542693eac82e4ef7add567 ?

**Comment by Lexblack** [comment]
![wowscrnshot_050916_161613](https://cloud.githubusercontent.com/assets/16202997/15114201/7f77227e-1601-11e6-9baf-77ce95752fec.jpg)
Seems fine now

**Comment by zelda1220** [comment]
Awesome! I will go take a look after I get home. :+1:

**Comment by zelda1220** [comment]
Thank you very much. Issue resolved.
