### ISSUE TITLE
Skada - GameToolTip Location

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#154]
Anyway to move the tooltip to the default location?

![wowscrnshot_050416_000309](https://cloud.githubusercontent.com/assets/7307335/15060271/9b7da968-12ee-11e6-9418-035b7a2eba20.jpg)

**Comment by Kkthnx** [comment]
You can adjust it from the Skada settings themselves. Look at my screenshot.

![wowscrnshot_050516_194909](https://cloud.githubusercontent.com/assets/1692977/15060636/b06e24c2-12fa-11e6-84db-286a0e152418.jpg)

**Comment by crumdidlyumshis** [comment]
Ah ok. I checked the settings, but it shows Default. Still shows the tooltip relative to the skada window instead of the default ElvUI location.

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI_AddOnSkins/commit/adbc2a4d118f859ebed5a3bb137c1c2ea8dd8558 ?
