### ISSUE TITLE
Target Frame - Middle Click - Set Focus (NULLED)

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#157]
Do I have something wrong?

![wowscrnshot_050516_182005](https://cloud.githubusercontent.com/assets/7307335/15060311/f311658e-12ee-11e6-9a78-a0fd948f657b.jpg)

**Comment by Bunny67** [comment]
disabled = function() return IsAddOnLoaded("Clique"); end

**Comment by crumdidlyumshis** [comment]
Ohhhh ok. I had no idea. Thank you!
