### ISSUE TITLE
Rogue Power Bar: Frequent Updates

### ISSUE THREAD

**Issue by webgee** [ElvUI/ElvUI#16]
Rogue power bars do not update frequently and there is no option to turn them on.

Druids can add
power.value.frequentUpdates = true;
at line 26 in players.lua but rogues cannot.

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI/commit/9e95ba604c6d300f57775ba431da55d79432ba58
It must be corrected

**Comment by webgee** [comment]
Solved the problem. Also adding

frame.Power.value.frequentUpdates = true;

below that will also put the value into frequent updates.
