### ISSUE TITLE
ElvUI_FriendsFrame - Addon Suggestion

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#160]
Hi Bunny67,

Would it be possible to port this addon to make use of the battle.net indicator?

https://valkyrie-wow.org/boards/index.php?showtopic=791

Just wanted to make use of the BNet Frame for private servers.

![world of warcraft 5_9_2016 4_29_14 pm](https://cloud.githubusercontent.com/assets/7307335/15128754/52b094e4-1603-11e6-8609-4cadf0261324.png)

**Comment by Bunny67** [comment]
if friends online then show BNet Frame?

**Comment by Kkthnx** [comment]
What he linked was an addon that uses the BNet system to show friends coming online and going offline. I think he wants support for that or you to add such a feature. So instead of it showing in chat Bunn67 has come online he wants it in the battle.net frame.

То, что он связан был аддон, который использует систему Bnet , чтобы показать друзьям приходить онлайн и перейти в автономный . Я думаю, что он хочет поддержку того или добавить такую ​​функцию . Так что вместо того, чтобы его показывать в чат Bunn67 пришел онлайн он хочет его в battle.net кадре .

via google translate

**Comment by crumdidlyumshis** [comment]
Exactly! Thank you @Kkthnx !

If a friend signs online, the BNet Frame appears. :)

**Comment by Bunny67** [comment]
I have not yet found a way to implement it
I do not know how to find the nickname of the incoming or outgoing of the world

**Comment by Kkthnx** [comment]
@crumdidlyumshis Can you maybe find a link to download the addon so the code can be looked at?

**Comment by Lexblack** [comment]
http://addons.us.to/addon/friendsframe

**Comment by Bunny67** [comment]
http://pastebin.com/eXkMsdGC Like how it works

**Comment by crumdidlyumshis** [comment]
@Bunny67 holy shit it works! Did you want to implement it into ElvUI? If so, this would be awesome! Or it can be a stand-alone addon. Thank you sir!

**Comment by crumdidlyumshis** [comment]
@Bunny67 https://github.com/crumdidlyumshis/BNetToast :)

It might be better to keep it as a stand-alone addon and just add the skins needed.

**Comment by crumdidlyumshis** [comment]
local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("BNetToast")) then return; end

function addon:BNetToast()
	local S = E:GetModule("Skins");
	BNToastFrameCloseButton:SetWidth(32);
	BNToastFrameCloseButton:SetHeight(32);
	BNToastFrameCloseButton:SetPoint("TOPRIGHT","BNToastFrame", 5, 5);
	S:HandleCloseButton(BNToastFrameCloseButton);
end

addon:RegisterSkin("BNetToast", addon.BNetToast);

**Comment by crumdidlyumshis** [comment]
All fixed and good to go! Thank you Bunny67!

https://github.com/Bunny67/BNetToast
https://github.com/Kkthnx/BNetToast
https://github.com/crumdidlyumshis/BNetToast

Closing.

**Comment by Luisu11** [comment]
how do i install it guys?

**Comment by Loaal** [comment]
* [Download](https://github.com/Bunny67/BNetToast/archive/master.zip)
* Unpack archive, rename the folder **BNetToast-master** to **BNetToast**
* Move **BNetToast** to `Wow\Interface\AddOns`
