### ISSUE TITLE
Suggestion - Friends List Name Colors

### ISSUE THREAD

**Issue by Lexblack** [ElvUI/ElvUI#161]
I have found an add-on that adds class colors to the friends list. The addon is for cataclysm client but it partially works with 3.3.5 client, it shows the colors but you can't access the options. If you want and have some free time, you can give it a look and maybe add this feature to ElvUI.

The 1.2 version seems to work best with 3.3.5.
http://www.wowinterface.com/downloads/info18256-FriendListColors.html#other

![wowscrnshot_051516_210226](https://cloud.githubusercontent.com/assets/16202997/15275985/4cbc8a7c-1ae3-11e6-96c4-09fb44d2e255.jpg)
![wowscrnshot_051516_210115](https://cloud.githubusercontent.com/assets/16202997/15275983/46efa228-1ae3-11e6-80e7-8e6c2b53a2d5.jpg)

**Comment by Bunny67** [comment]
addon does not work :(

**Comment by crumdidlyumshis** [comment]
I think he is asking to add the colors to to elvui based on this addon.

**Comment by Bunny67** [comment]
addon does not work even partially
And I not found a code there, which changes friend list as in the screenshot

**Comment by crumdidlyumshis** [comment]
I haven't tried out the addon, but @Lexblack said 1.2 works best. http://www.wowinterface.com/downloads/getfile.php?s=f125f6cebf0636e76d2847d0db397384&id=18256&aid=63601

**Comment by Bunny67** [comment]
Online friends - can make
offline friends - I do not know how to do

**Comment by crumdidlyumshis** [comment]
Probably have to do some sort of caching method.

**Comment by Bunny67** [comment]
Yes. But it is not in the addon

**Comment by Bunny67** [comment]
![wowscrnshot_080916_215209](https://cloud.githubusercontent.com/assets/5816685/17529359/a5ff729e-5e7b-11e6-9911-dc5c0c9d54eb.jpg)

**Comment by Apollyonn** [comment]
I took the code of this addon and i have used it in the 4.3.4 version. http://pastebin.com/V4mBLwwD
I'm not 100% sure but i think the problem here  is with the Scroll Frame Offset.
![wowscrnshot_080916_224634](https://cloud.githubusercontent.com/assets/19589902/17531223/a61cc8be-5e83-11e6-9157-2f5e99c2d989.jpg)
![wowscrnshot_080916_224650](https://cloud.githubusercontent.com/assets/19589902/17531228/a94b9fd8-5e83-11e6-96f7-c89caf07d26d.jpg)

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI_FriendsListColor
There is a nasty bug :(

**Comment by crumdidlyumshis** [comment]
Im not sure what but your seeing @Bunny67 ?

Close if needed. Lets get these bug reports down to zero!
