### ISSUE TITLE
Target Unitframe: Name Unmovable

### ISSUE THREAD

**Issue by Anonic** [ElvUI/ElvUI#163]
No options in the Name category for Target in Unitframes do anything for moving it. You can't modify the offset, alignment, or attached location.

**Comment by datbunneh** [comment]
Just cut the string, create a custom text and paste it there.

**Comment by Lexblack** [comment]
Can you post a screenshot of your settings? like Unitframes>Target?

**Comment by Anonic** [comment]
[Screenshot](https://i.imgur.com/fNS6HI8.jpg) of setting.

Using Bunny, Kkthnx, and AddonSkins as well.

**Comment by Kkthnx** [comment]
Shouldn't be an issue with my part. Bit outdated yes but nothing should mess with it I don't think. Disable all your addon and keep ElvUI and the Config enabled and see if you still have the issue.

**Comment by Anonic** [comment]
Issue persists with only ElvUI and Config enabled.

**Comment by Lexblack** [comment]
Untick toggle on npc

**Comment by Anonic** [comment]
Ooh I see. Interesting it changes anchor point. Thanks.
