### ISSUE TITLE
Mac Options

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#17]
First off, AWESOME JOB on backporting this wonderful addon for such a wonderful version of World of Warcraft!! Thank you!

![screen shot 2015-08-31 at 4 57 10 pm](https://cloud.githubusercontent.com/assets/7307335/9591508/70ff7fe6-5001-11e5-9ebf-9b024d6f4ee1.png)

Could you add this into the repository? Thanks!

![screen shot 2015-08-31 at 4 47 20 pm](https://cloud.githubusercontent.com/assets/7307335/9591287/026a1d80-5000-11e5-801d-d57a67b69b81.png)

![screen shot 2015-08-31 at 4 43 07 pm](https://cloud.githubusercontent.com/assets/7307335/9591216/87e78e8a-4fff-11e5-89a8-2a1f188512b3.png)
![screen shot 2015-08-31 at 4 43 43 pm](https://cloud.githubusercontent.com/assets/7307335/9591217/87e9d172-4fff-11e5-8d11-9d0e348aa558.png)

**Comment by Bunny67** [comment]
fix
