### ISSUE TITLE
EXP and REP - Data Bars

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#180]
They appear to work fine, however, they do not seem to save correctly. I have to always reset them back to the settings I want. 

Reputation always disables. Also, a few settings are buggy in them. Needs finessing.

**Comment by Bunny67** [comment]
checked, I have everything working

**Comment by crumdidlyumshis** [comment]
Hmm I will recheck later and test again.

**Comment by crumdidlyumshis** [comment]
Seems to be working fine now. Closing.
