### ISSUE TITLE
Time Manager Frame - Can't Toggle

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#186]
When I click on the time Data Text it will show the calendar, but when I right click it will not show the Time Manager Frame.

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI/commit/6b492969c4842e1bf61ff76ee58add023a034ac9 ?

**Comment by crumdidlyumshis** [comment]
YES thank you! <3
