### ISSUE TITLE
Map Tooltip Level

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#19]
I noticed the tooltip on the map sits behind the marks on the map.

![world of warcraft 9_9_2015 12_36_54 pm](https://cloud.githubusercontent.com/assets/7307335/9794300/f55fafbc-57af-11e5-90ef-33cb2453b94e.png)

**Comment by Bunny67** [comment]
Не удалось воспроизвести :(

**Comment by Bunny67** [comment]
Perhaps corrected
