### ISSUE TITLE
Simple Rare Elite

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#2]
Hey first off, AWESOME job on backporting this addon. This is not really an issue, but a request per-say. Would you happen to be able to backport http://www.tukui.org/addons/index.php?act=view&id=257 for this version of ElvUI? I will love you forever!

Thanks.

**Comment by Bunny67** [comment]
And so should work just tick "Obsolete modification".

Google translete :(

Ru
Должно и так работать, просто поставить галочку "Устаревшие модификации".
