### ISSUE TITLE
ElvUI Settings - Button Translation

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#20]
ElvUI > UnitFrames > Player Frame > Castbar

I think its supposed to say Show/Hide?

![world of warcraft 9_10_2015 11_56_15 am](https://cloud.githubusercontent.com/assets/7307335/9794899/5f6d6d38-57b3-11e5-8c07-86ce9bbe579c.png)

![world of warcraft 9_10_2015 11_56_48 am](https://cloud.githubusercontent.com/assets/7307335/9794902/6212a4a4-57b3-11e5-8a7e-31afe064e8b6.png)

**Comment by Bunny67** [comment]
fix
