### ISSUE TITLE
Feature Request: Skada/Recount/Omen Toggle Tab

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#202]
Would it be possible when skada/recount/omen is shown, there can be an option to show a chat tab next to Loot/Trade to toggle skada or recount?

Before:

![world of warcraft 8_27_2016 5_27_59 pm](https://cloud.githubusercontent.com/assets/7307335/18030467/6c5731c6-6c7c-11e6-9255-8190c44bb9ac.png)

Check: Enable Below Tab

![world of warcraft 8_27_2016 5_24_07 pm](https://cloud.githubusercontent.com/assets/7307335/18030468/710aba8a-6c7c-11e6-90cb-7e9e6983eb78.png)

After:

![world of warcraft 8_27_2016 5_25_37 pm](https://cloud.githubusercontent.com/assets/7307335/18030469/79a89ea0-6c7c-11e6-8587-c59e4c824075.png)

@Apollyonn or @Bunny67

**Comment by Bunny67** [comment]
Yes. I think tomorrow will in AddonSlins

**Comment by crumdidlyumshis** [comment]
Awesome! Thank you Bunny!

**Comment by Bunny67** [comment]
check

**Comment by crumdidlyumshis** [comment]
https://github.com/ElvUI/ElvUI_AddOnSkins
