### ISSUE TITLE
Target Frame - Names Get Cut Off

### ISSUE THREAD

**Issue by Rennekae** [ElvUI/ElvUI#207]
![wowscrnshot_083116_161046](https://cloud.githubusercontent.com/assets/21370722/18144622/83cf167c-6f95-11e6-8351-ffbc66802ac0.jpg)

Not the best example since it's only missing one letter but, as the above screenshot shows, target names are being cut short. 

It seems to happen if the name is more than a certain amount of characters (i.e. "Darkfiend Assas[sin]" is the same number of characters as "Wild Dreamrunne[r]"), but I may be wrong. I haven't seen it happen with the party frames yet, but that might be because no one's name has been long enough; I haven't checked. 

I've tried messing with the settings in Unit Frames > Target Frame - changing the width of the bar so it had more space for more characters, playing with the text offset and where it's attached,etc. and I've already disabled "Text Toggle on NPC" in the hopes that the 'Name' parameter would allow for more space than the 'Power one', but no luck. I know this isn't a huge issue but it's aesthetically unappealing and it bothers me.

Does anyone know if/how this can be fixed? Thanks in advance!

**Comment by Bunny67** [comment]
This version of the addon to 3.3.5a
Please state your problem here: http://git.tukui.org/Elv/elvui/issues

**Comment by crumdidlyumshis** [comment]
I will say though, legion sure looks pretty! ^^

**Comment by Rennekae** [comment]
It definitely is! They put a lot of effort into it. :3

________________________________
