### ISSUE TITLE
Quest Objectives - Show/Hide Button

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#21]
The button starts off large when logging into the game, but shows small after you toggle it. Also, I think it needs to have a + symbol rather than a - symbol when maximizing.

![world of warcraft 9_10_2015 11_43_28 am](https://cloud.githubusercontent.com/assets/7307335/9794998/e52c4da4-57b3-11e5-82fa-a7f3f3c8c1db.png)

![world of warcraft 9_10_2015 11_44_22 am](https://cloud.githubusercontent.com/assets/7307335/9795000/e7a26280-57b3-11e5-9c4d-04a96757a530.png)

**Comment by Bunny67** [comment]
fix
