### ISSUE TITLE
Help & Support - Title

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#23]
![world of warcraft 9_10_2015 11_54_42 am](https://cloud.githubusercontent.com/assets/7307335/9795055/28084a06-57b4-11e5-9aab-8b90b4f58c78.png)

Need I say more? Haha

**Comment by Bunny67** [comment]
It was not possible to fix

**Comment by Bunny67** [comment]
The rest of the bugs corrected within 1-2 hours

**Comment by Bunny67** [comment]
fix
