### ISSUE TITLE
Player Pet Frame

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#26]
Would it be possible to skin the Resistances icons on the right and possibly the Happy/Sad/Unhappy icon? Thank you! Your an amazing developer! :)

![wowscrnshot_091315_153823](https://cloud.githubusercontent.com/assets/7307335/9838943/2f4497c4-5a30-11e5-87fc-fe3906c71cc9.jpg)

**Comment by duckempire** [comment]
The pet happiness icon would be a great addition :+1:

**Comment by Bunny67** [comment]
fix
