### ISSUE TITLE
Taints. If you care for them here you go! :D

### ISSUE THREAD

**Issue by Kkthnx** [ElvUI/ElvUI#3]
5/22 17:47:53.555  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:47:53.555      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:47:53.555      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:47:53.555      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:47:53.555      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:47:53.555  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:47:53.555      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:47:53.555      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:47:53.555      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:47:53.555      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:47:53.555  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:47:53.555      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:47:53.555      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:47:53.555      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:47:53.555      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:47:53.572  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:47:53.572      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:47:53.572      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:47:53.572      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:47:53.572      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:47:55.222  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:47:55.222      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:47:55.222      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:47:55.222      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:47:55.222      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:47:55.251  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:47:55.251      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:47:55.251      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:47:55.251      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:47:55.251      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:47:55.251  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:47:55.251      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:47:55.251      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:47:55.251      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:47:55.251      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:47:55.261  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:47:55.261      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:47:55.261      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:47:55.261      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:47:55.261      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:41.786  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:41.786      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:41.786      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:48:41.786      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:48:41.786      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:41.811  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:41.811      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:41.811      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:48:41.811      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:48:41.811      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:46.276  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:46.276      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:46.276      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:48:46.276      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:48:46.276      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:46.276  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:46.276      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:46.276      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:48:46.276      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:48:46.276      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:46.276  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:46.276      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:46.276      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:48:46.276      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:48:46.276      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:46.296  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:46.296      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:46.296      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:48:46.296      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:48:46.296      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:46.604  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:46.604      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:46.604      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:48:46.604      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:48:46.604      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:46.639  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:46.639      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:46.639      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:48:46.639      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:48:46.639      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:54.286  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:54.286      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:54.286      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:48:54.286      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:48:54.286      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:54.306  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:54.306      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:54.306      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:48:54.306      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:48:54.306      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:57.069  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:57.069      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:57.069      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:48:57.069      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:48:57.069      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:57.087  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:57.087      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:57.087      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:48:57.087      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:48:57.087      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:59.057  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:59.057      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:59.057      Interface\FrameXML\UIParent.lua:2421 UIFrameFadeIn()
5/22 17:48:59.057      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:153 ?()
5/22 17:48:59.057      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90
5/22 17:48:59.074  An action was blocked in combat because of taint from ElvUI - ElvUI_StanceBar:Show()
5/22 17:48:59.074      Interface\FrameXML\UIParent.lua:2400 UIFrameFade()
5/22 17:48:59.074      Interface\FrameXML\UIParent.lua:2431 UIFrameFadeOut()
5/22 17:48:59.074      Interface\AddOns\ElvUI\modules\actionbars\actionbars.lua:158 ?()
5/22 17:48:59.074      Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:90

**Comment by Bunny67** [comment]
Google translete:
It's just not correct :( Think about the error.

Ru:
Это просто так не исправить :( Подумаю над этой ошибкой.
