### ISSUE TITLE
Auctionator - Button Select Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#30]
When dragging something to the sell tab, the three tabs appear. Selecting either tab, Current, Past, or Other shows a broken skin.

![wowscrnshot_091515_171732](https://cloud.githubusercontent.com/assets/7307335/9891718/0a021366-5bce-11e5-88f0-ffb05ef3d119.jpg)

**Comment by Bunny67** [comment]
Fixed in the next hour
