### ISSUE TITLE
World Map - Extremely large font in dropdown

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#31]
This is in the latest version.

Also, it looks like the Zoom button is a little close to the right of the dropdown. Maybe move it to the right some more?

Thank you for fixing the tooltip strata level! :)

![wowscrnshot_092015_234645](https://cloud.githubusercontent.com/assets/7307335/9985531/259abc08-5ff3-11e5-9dd5-062623e99690.jpg)

**Comment by Bunny67** [comment]
fix
