### ISSUE TITLE
Pet/Spellbook button skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#32]
Latest version.

![wowscrnshot_092015_234756](https://cloud.githubusercontent.com/assets/7307335/9985580/fb8d14be-5ff3-11e5-8cbd-ab321d41322d.jpg)

**Comment by Bunny67** [comment]
fix

**Comment by crumdidlyumshis** [comment]
One more thing - The spacing

![wowscrnshot_092115_205010](https://cloud.githubusercontent.com/assets/7307335/10009481/3f5fd56e-60a3-11e5-9939-4979954aee75.jpg)
