### ISSUE TITLE
Game Options Menu - AddOns button spacing

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#34]
Lol, yes I know... Really? I tend to be a perfectionist with anything haha.

Looks like the button could go up a pixel xD

![wowscrnshot_092115_003601](https://cloud.githubusercontent.com/assets/7307335/9985821/ffc0cdaa-5ff8-11e5-96dd-76a393228539.jpg)

**Comment by Bunny67** [comment]
![wowscrnshot_092115_165531](https://cloud.githubusercontent.com/assets/5816685/9993740/ed830ffc-6081-11e5-9fec-f5514d94f487.jpg)
Full screen

**Comment by crumdidlyumshis** [comment]
Wierd! I tried all sorts of screen resolutions and it kept showing that 1px gap. No biggy if its not fixable :D Just one of those OCD moments haha.

**Comment by Bunny67** [comment]
![wowscrnshot_092115_200206](https://cloud.githubusercontent.com/assets/5816685/9998813/ba6b5d3a-609b-11e5-9c1e-f03aacfa923c.jpg)
