### ISSUE TITLE
Glyphs Frame - Opacity Bug

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#36]
Not sure if I bugged it, or if its just like this. Looks like its 100% Opacity.

![wowscrnshot_092315_142739](https://cloud.githubusercontent.com/assets/7307335/10057299/2f28884a-6205-11e5-9817-85f2963b7a29.jpg)

**Comment by Bunny67** [comment]
If you make clear, it will be seen the lower frame

**Comment by crumdidlyumshis** [comment]
Making it clear would look better. It will show the hidden information as well. Just needs to be tweaked.

![untitled](https://cloud.githubusercontent.com/assets/7307335/10076569/d328a212-62a1-11e5-9150-07d4a8a9ba24.png)
![wowscrnshot_092415_094643](https://cloud.githubusercontent.com/assets/7307335/10076572/d5ba0336-62a1-11e5-8849-2ec32caca6b4.jpg)

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI/commit/45b5c585bca9bceded3ce48305b8db820a36f141 Better?

**Comment by crumdidlyumshis** [comment]
Oh awesome! Thanks! Your the man! :+1:
