### ISSUE TITLE
Various Button Tooltips

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#37]
I think the tooltips are supposed to show up on the bottom right corner of each button or on the default GameTooltip location, and also show the keyboard shortcut button beside the text.

![wowscrnshot_092315_142821](https://cloud.githubusercontent.com/assets/7307335/10057336/58f3c2a2-6205-11e5-991d-3049da0afb1c.jpg)
![wowscrnshot_092315_141640](https://cloud.githubusercontent.com/assets/7307335/10057335/58f31424-6205-11e5-8242-91e3399d17a2.jpg)
![wowscrnshot_092315_141647](https://cloud.githubusercontent.com/assets/7307335/10057337/58fe1c98-6205-11e5-9f93-1c39783ff660.jpg)

**Comment by Bunny67** [comment]
it is impossible to change the position of tips :(
