### ISSUE TITLE
ElvUI Actionbars -  Backdrop Opacity (Not sure how to reproduce)

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#38]
Very strange bug with the action-bars backdrop. I was setting my spelled to my actionbar buttons and then it made the buttons backdrop become 100% opac.

Before:

![wowscrnshot_092315_145644](https://cloud.githubusercontent.com/assets/7307335/10057501/2af82e50-6206-11e5-9a29-887a3bb649eb.jpg)

After:

![wowscrnshot_092315_145646](https://cloud.githubusercontent.com/assets/7307335/10057504/30045bd0-6206-11e5-990a-d6a5d7f815e5.jpg)

**Comment by Bunny67** [comment]
![1](https://cloud.githubusercontent.com/assets/5816685/10075295/abea501a-62dd-11e5-92e7-6c1568e3be49.png)

**Comment by crumdidlyumshis** [comment]
Weird, okay it fixed that for now. I will let you know if it bugs out again.
