### ISSUE TITLE
World Map - Interface action failed because of an addon

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#39]
I think when I had the map open, I flew past an mob and it glitched out the map. 

Ill try to re-produce

![wowscrnshot_092415_205210](https://cloud.githubusercontent.com/assets/7307335/10091366/0f8d0bea-6300-11e5-80a9-021f0174eaa1.jpg)

**Comment by Bunny67** [comment]
fix, need test
