### ISSUE TITLE
Interface Options - Social - Click to Focus button skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#40]
![wowscrnshot_092415_204055](https://cloud.githubusercontent.com/assets/7307335/10091372/2a24f346-6300-11e5-8631-a76836214733.jpg)

**Comment by Bunny67** [comment]
fix

**Comment by crumdidlyumshis** [comment]
Not sure if its really fixed. The button is missing.

![2a24f346-6300-11e5-8631-a76836214733](https://cloud.githubusercontent.com/assets/7307335/10198342/3d2337a4-6761-11e5-83cf-29e5bd6318f0.jpg)

**Comment by Bunny67** [comment]
It is shown only when chatStyle == "im", but chatStyle == "im" is not supported addon


Ru: Она показывается только когда chatStyle == "im", но chatStyle == "im" не поддерживается аддоном

**Comment by crumdidlyumshis** [comment]
Ohhhh gotcha. Thanks!
