### ISSUE TITLE
no totem classbars for shaman :(

### ISSUE THREAD

**Issue by orsvajda** [ElvUI/ElvUI#43]
I found that there's no totem classbars for shamans (in the unit frames) - just like DKs runes - it should display like that.

**Comment by Bunny67** [comment]
![wowscrnshot_093015_184624](https://cloud.githubusercontent.com/assets/5816685/10198206/a94a2c66-67a3-11e5-8a16-6d82381359ee.jpg)

**Comment by orsvajda** [comment]
-.-"
Can you read? UNIT FRAMES
https://youtu.be/EXTS2wLcYqk?t=1m46s
Talking about the UNIT FRAME totem bar, just like in the video (red,yellow,blue,green).
When he puts down the totems you can see that those colors will light up. Now my friend, I'm talking about that, because THAT one is truly missing... I know this shitty totem bar actually works (which you showed me on your SS), but I need this one either.

**Comment by Bunny67** [comment]
На видео очень старая версия. Те индикаторы тотемов были удалены, были добавлены более информативные.

![wowscrnshot_100215_170828](https://cloud.githubusercontent.com/assets/5816685/10248484/75e97328-6928-11e5-8ff5-2e68b4c4a8dd.jpg)

**Comment by Kkthnx** [comment]
orsvajda, there are tons of other addons that will suit what you are looking for. Also have some respect for people man. Bunny takes their times to do all this so just be happy. Take some time to look at wowinterface and curse for other addons to suit your needs.

**Comment by orsvajda** [comment]
You are right, I'm sorry for my immature behavior. I was upset because he didn't read through what I was meaning for :) This addon is great, I was just trying to help with this bug report, to improve the addon. Bunny, no they didn't remove it, I tried it today and it works for me! You can see that the classbar is working in the russian version (DL from: https://getaddon.com/2011-01-31-11-44-55/772-elvui-406-ru ). Don't get me wrong - I'm trying to help to improve a better add-on.
![wowscrnshot_100215_201024](https://cloud.githubusercontent.com/assets/11787742/10254065/afb085b0-6941-11e5-9952-76c180d0eefe.jpg)
