### ISSUE TITLE
Raid difficulty

### ISSUE THREAD

**Issue by Sdw8** [ElvUI/ElvUI#45]
When you call the context menu of the frame the player, there is no choice of difficulty dungeon / raid.

**Comment by Bunny67** [comment]
in raid
![wowscrnshot_093015_184205](https://cloud.githubusercontent.com/assets/5816685/10198135/637c4a2a-67a3-11e5-8970-98161355eaf9.jpg)

solo
![wowscrnshot_093015_184250](https://cloud.githubusercontent.com/assets/5816685/10198158/7b15170c-67a3-11e5-8299-b2df359e8c90.jpg)

**Comment by Sdw8** [comment]
in raid
![wowscrnshot_093015_221016](https://cloud.githubusercontent.com/assets/14907962/10203789/ca9e8f70-67c0-11e5-94f9-60ac72e27c2a.jpg)


solo
![wowscrnshot_093015_221038](https://cloud.githubusercontent.com/assets/14907962/10203780/bbf17564-67c0-11e5-9481-6863d161f0c8.jpg)

**Comment by Bunny67** [comment]
Попробуй отключить все аддоны, и включить только ElvUI

**Comment by Sdw8** [comment]
Отключил все аддоны кроме ElvUI. То же самое. Может можно как-то связаться с тобой что бы разобраться с этим?

**Comment by Bunny67** [comment]
Сделай копию папки WTF, либо переименуй, удали старую(если переименовал, новая сама появится), ну и запусти вов, если проблема останется, то даже не знаю как ее решить. Отпиши о результате

**Comment by Sdw8** [comment]
![wowscrnshot_100115_165337](https://cloud.githubusercontent.com/assets/14907962/10222567/6dd7e01e-685d-11e5-912d-118b2a43726d.jpg)

**Comment by Bunny67** [comment]
У меня на русском и английском все норм, без аддона показывает меню?

**Comment by Sdw8** [comment]
Не отображается. О_о. Странно когда использовал раньше еще другую версию ElvUI было все норм и с ним и без него. Что не так... Сейчас попробую может удалить все Blizzard аддоны. Извиняюсь за ошибочную тему.

**Comment by Bunny67** [comment]
Хм, но у меня и на 1-м лвле показывает сложность рейда.

**Comment by Sdw8** [comment]
У меня на 80 отображается он правда на другом аккаунте. А на другом только 1 персонаж и он не 80, и на нем не отображается ни с аддоном ни без него.

**Comment by Bunny67** [comment]
Если на 80-м все норм, то я думаю не стоит искать проблему :)

**Comment by Sdw8** [comment]
Сейчас попробую на первом аккаунте создать персонажа и проверить если не будет отображаться тогда норм. А если будет и на 1 то что-то не так.

**Comment by Sdw8** [comment]
Блин, персонаж 42 уровня без рейда отображается сложность только рейда... А на 2 персонаже что скрины выше 61 уровень и нету ничего.

**Comment by Bunny67** [comment]
2-й перс на 2-м акке?

**Comment by Sdw8** [comment]
Да.

**Comment by Sdw8** [comment]
Вообщем на 1 аккаунте на 80 уровне отображается все и с аддоном и без него. На этом же аккаунте 42 уровень и 1 пробовал там только сложность рейда. На другом же аккаунте который создавал относительно недавно ни на 61 ни на 1 нету ничего ни с аддоном, ни без него.

**Comment by Bunny67** [comment]
Даже не знаю, у меня на 2-м акке где нет 80-го лвла, отображается только сложность рейда с аддоном и без

**Comment by Bunny67** [comment]
Видимо какой то баг со стороны клиента/сервера.

**Comment by Bunny67** [comment]
На новом аккаунте(популярного русского сервера) такой же баг.

**Comment by Sdw8** [comment]
Вот я удалил полностью WTF и Cash. Это персонаж 61 на новом акке без аддонов.
![wowscrnshot_100115_190900](https://cloud.githubusercontent.com/assets/14907962/10226473/53775ee4-6870-11e5-93bf-d169d665c364.jpg)
На старом же:
![wowscrnshot_100115_191229](https://cloud.githubusercontent.com/assets/14907962/10226551/c6636c86-6870-11e5-847b-715fc9560253.jpg)
Это может быть из-за сервера? Мне казалось это все в клиенте происходит. Попробовал поменять сложность макросом и все прекрасно работает.

**Comment by Bunny67** [comment]
Походу с 65-го лвла откроется

**Comment by Bunny67** [comment]
По крайне мере так в клиенте.

**Comment by Sdw8** [comment]
Но ведь на скрине 20 уровень и есть хотя бы сложность рейда. Хотя не понятно почему только рейда.

**Comment by Bunny67** [comment]
Хз, в клиенте нашел только что она должна показаться на 65 лвлв или 66

elseif ( value == "DUNGEON_DIFFICULTY" ) then
	if ( UnitLevel("player") < 65 and GetDungeonDifficulty() == 1 ) then
		UnitPopupShown[UIDROPDOWNMENU_MENU_LEVEL][index] = 0;
	end
elseif ( value == "RAID_DIFFICULTY" ) then
	if ( UnitLevel("player") < 65 and GetRaidDifficulty() == 1 ) then
		UnitPopupShown[UIDROPDOWNMENU_MENU_LEVEL][index] = 0;
	end

**Comment by Bunny67** [comment]
Хотя мб это и не то

**Comment by Sdw8** [comment]
А возможно ли в аддон вбить чтобы они показывались постоянно с 1 уровня?

**Comment by Bunny67** [comment]
Да можно

Добавь в часто используемый аддон:

hooksecurefunc("UnitPopup_HideButtons", function()
	local dropdownMenu = UIDROPDOWNMENU_INIT_MENU;
	
	for index, value in ipairs(UnitPopupMenus[dropdownMenu.which]) do
		if(value == "DUNGEON_DIFFICULTY") then
			UnitPopupShown[UIDROPDOWNMENU_MENU_LEVEL][index] = 1;
		elseif(value == "RAID_DIFFICULTY") then
			UnitPopupShown[UIDROPDOWNMENU_MENU_LEVEL][index] = 1;
		end
	end
end);

**Comment by Sdw8** [comment]
Можно в ElvUI любой файл lua?

**Comment by Bunny67** [comment]
Да, но при обновлении он пропадет, либо создай отдельный аддон

**Comment by Sdw8** [comment]
Я не шарю в этом)

**Comment by Bunny67** [comment]
А лучше докачайся до 65го лвла :)

**Comment by Sdw8** [comment]
Все работает) Да было бы неплохо чтобы оно в нем всегда было) Но проблема отсутствия таймера выстрела это плохо. Ладно бы на кате можно на ходу стрелять. А включать кварц ради одного таймера тоже не очень.

**Comment by Sdw8** [comment]
Еще если можно добавь в рамки юнитов у питомцу [happiness]. Отображение в виде смайлика настроения очень помогает.

**Comment by Bunny67** [comment]
Таймер сделал доп аддоном, https://github.com/ElvUI/ElvUI_SwingBar

Скажи файлообменник, закину отдельным аддоном скрипт на меню

**Comment by Sdw8** [comment]
http://rghost.ru/

**Comment by Bunny67** [comment]
http://rghost.ru/65bwXfCVn

**Comment by Sdw8** [comment]
Спасибо огромное, пока не закрыл тему последний вопрос для чего используется ElvUI_RightClick и ElvUI_Bunny там Time tracker тоже какой-то есть.

**Comment by Bunny67** [comment]
ElvUI_RightClick правый клик по кнопке = каст на себя

ElvUI_Bunny это мои модификации интерфейса, щас там "плюшки" с офф версии, такие как окно персонажа, отсчет времени до начала бг и т.д

**Comment by Sdw8** [comment]
SwingBar добавил фрейм но он ничего не отображает ни в ближнем не в дальнем бою.

**Comment by Bunny67** [comment]
Он по дефолту отключен

**Comment by Bunny67** [comment]
Смотри в настройках Игрока

**Comment by Sdw8** [comment]
Нашел уже) Огромное спасибище тебе) Закрывай тему.

**Comment by Bunny67** [comment]
:)
