### ISSUE TITLE
Party Frames - 3D Overlay

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#48]
When 3D > Overlay is selected, it doesnt show the 3D models until they go far away. Otherwise, it just turns black.

![wowscrnshot_100115_153034](https://cloud.githubusercontent.com/assets/7307335/10272366/3063b45e-6ae4-11e5-8e6b-4dcc2fb93925.jpg)

**Comment by Bunny67** [comment]
It must be corrected
