### ISSUE TITLE
Target Frame - Seriously bugged

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#51]
If you target a person or npc and then target another player or npc, it wont update the Name or Level or 3D Model

![wowscrnshot_100615_213717](https://cloud.githubusercontent.com/assets/7307335/10327942/7a4c1a12-6c73-11e5-8f08-9c2311314882.jpg)

![wowscrnshot_100615_213719](https://cloud.githubusercontent.com/assets/7307335/10327946/ac48dea6-6c73-11e5-8acd-a91955d998d8.jpg)

**Comment by LiNK2088** [comment]
Confirmed

**Comment by Bunny67** [comment]
Should be corrected, check

**Comment by crumdidlyumshis** [comment]
Looks like it works now! Thank you!

**Comment by LiNK2088** [comment]
Yup works now

**Comment by Icenova20** [comment]
I just wanted to thank you for doing this. You are one of the most active devs i've ever seen, you don't get enough thanks.

**Comment by crumdidlyumshis** [comment]
@Bunny67 Agreed @Icenova20 he deserves a huge thank you! I never see active developers like this. Hes not even getting paid to do this! He is just doing out of the kindness of his heart and fun :) Thank you again @Bunny67

**Comment by LiNK2088** [comment]
All hail Bunny!

**Comment by crumdidlyumshis** [comment]
I think this can be closed now. I dont see any issues for now with the target frames. Seems to be working flawlessly.
