### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by Sdw8** [ElvUI/ElvUI#53]
Можно ли добавить сортировку для Guild Bank'a? Или если считаете что он не нужен, то чтобы добавить ее отдельно.

**Comment by Bunny67** [comment]
Я думаю будет лучше воспользоватся отдельным аддоно, так как единицам понадобится эта функция :) Например http://www.curse.com/addons/wow/sushi-sort есть для 3.3.5

**Comment by Sdw8** [comment]
Хорошо, спасибо.

**Comment by Frixen** [comment]
Подниму вопрос, хотелось бы видеть эту функцию именно в ElvUI
