### ISSUE TITLE
Copy Chat Broken

### ISSUE THREAD

**Issue by squee666** [ElvUI/ElvUI#54]
The copy Chat Function has been broken for awhile after you updated it. Dunno what revision it started breaking at.

Also the copy url from directly clicking in chat does not work.

**Comment by Bunny67** [comment]
Mark also does not work?

Ru: Все так же не работает?

**Comment by squee666** [comment]
nope

**Comment by Bunny67** [comment]
The conflict with what some addon or something changed in the settings. Try to "Install" to reset the chat

**Comment by Bunny67** [comment]
I did not play

**Comment by Bunny67** [comment]
check
