### ISSUE TITLE
AFK - Chat Relocation

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#56]
If you wait 5 or so minutes to let your character go AFK, the chat will move up to the top left of the screen and go back when not AFK. This WILL NOT work if you just simply /afk. Wait 5 minutes.

![screenshot469187](https://cloud.githubusercontent.com/assets/7307335/10418880/aa84b6e6-702c-11e5-826a-243485e716fa.jpg)

**Comment by crumdidlyumshis** [comment]
![screenshot435729](https://cloud.githubusercontent.com/assets/7307335/10595435/89f02b3c-769d-11e5-9523-d766f6d36723.jpg)

**Comment by crumdidlyumshis** [comment]
![screenshot435705](https://cloud.githubusercontent.com/assets/7307335/10595439/a1de0d90-769d-11e5-8f06-f0c92122084e.jpg)

**Comment by Bunny67** [comment]
I do not understand about what it :(
I write /afk chat goes up, did not understand the nature of the error :(

Ru: Не понял про что речь :(
Пишу /afk чат идет вверх, не понял суть ошибки :(

**Comment by crumdidlyumshis** [comment]
Is the chat supposed to hide?

**Comment by Bunny67** [comment]
Chat shown in the afk and shows guild messages and private messages

**Comment by crumdidlyumshis** [comment]
Ah okay. I thought this was a bug, didnt know it was a feature. Haha. :)
