### ISSUE TITLE
Boss frames not showing

### ISSUE THREAD

**Issue by GhostAlgalon** [ElvUI/ElvUI#6]
I'm not sure if it's only on my end but for me boss frames  doesn't show up with this. Tried on all bosses in ulduar, didn't work. I disabled the DBM Boss frames aswell

**Comment by Bunny67** [comment]
Not quite sure about that question :( If mono attach skreenshot.
Google translete

Ru: Не совсем понял про что идет речь :( Если моно приложите скрееншот.
