### ISSUE TITLE
Item Border Quality Color - Mail

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#62]
![world of warcraft 10_12_2015 4_30_28 pm](https://cloud.githubusercontent.com/assets/7307335/10439334/dab976f8-70fe-11e5-9959-5377d646cecd.png)
![world of warcraft 10_12_2015 4_30_57 pm](https://cloud.githubusercontent.com/assets/7307335/10439336/dc0c5bd8-70fe-11e5-93cc-f9a387569ff3.png)

**Comment by Bunny67** [comment]
inbox button not support quality

**Comment by crumdidlyumshis** [comment]
Close?

**Comment by crumdidlyumshis** [comment]
I think this is working? Keep open if not. Close if needed.

**Comment by Bunny67** [comment]
In part, all will not work
