### ISSUE TITLE
Item Border Quality Color - Crafting

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#63]
![world of warcraft 10_12_2015 4_41_33 pm](https://cloud.githubusercontent.com/assets/7307335/10439562/5ac26e30-7100-11e5-9723-4433c5c0ead6.png)

**Comment by Bunny67** [comment]
Do not fail to realize in full :( as the function GetItemInfо takes information from the history, that is to say, if object you have never had, he did not indicate what color object

http://wowprogramming.com/docs/api/GetItemInfo

**Comment by Bunny67** [comment]
On the other i have not yet found ways to implement:(

Ru: По другому я не нашел способа реализации:(

**Comment by Bunny67** [comment]
![wowscrnshot_101315_194653](https://cloud.githubusercontent.com/assets/5816685/10461716/69b26fec-71e3-11e5-92f6-b678e0f2c192.jpg)

**Comment by Bunny67** [comment]
Implement will not work :(

Ru: Реализовать не получится :(
