### ISSUE TITLE
Party Frames - Healcomm

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#65]
When casting on a player, the approximate amount to be healed shows white.

![wowscrnshot_101115_235403](https://cloud.githubusercontent.com/assets/7307335/10440869/8543c85e-7108-11e5-8e09-c45b3e850cca.jpg)

**Comment by Bunny67** [comment]
У меня не воспроизводится:(

Need google translate :)

**Comment by crumdidlyumshis** [comment]
http://www.freetranslation.com/ has more accurate translations.

Looks like you said, I cannot reproduce?

Я еще раз взглянуть и позвольте вам знать.
I will take another look and let you know.

**Comment by Bunny67** [comment]
Yes

**Comment by Bunny67** [comment]
There had to be corrected

Ru: Должно было быть исправлено
