### ISSUE TITLE
Chat Panel Toggle - EXP & REP Bars

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#66]
When hiding the left or right chat, the experience and reputation bars do not hide.

![wowscrnshot_101115_223218](https://cloud.githubusercontent.com/assets/7307335/10440896/b967269e-7108-11e5-92c1-ad28f321e618.jpg)

**Comment by Bunny67** [comment]
This is as it should be, you can use "When you hover your mouse" by selecting the settings

Ru: Так и должно быть, можно использовать "При наведении" выбрав в настройках

**Comment by Bunny67** [comment]
But I'll think about it as soon as you can to resolve the problem

Ru: Но я подумаю как можно решить эту проблему

**Comment by crumdidlyumshis** [comment]
Ah, okay. It just seemed kind of strange. But if that's how it should be, then so be it. Haha.
