### ISSUE TITLE
Skada Damage Meters - Toggle Chat

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#67]
When Skada is visible, shouldn't the chat behind it hide?

![wowscrnshot_101115_230445](https://cloud.githubusercontent.com/assets/7307335/10440932/171157e2-7109-11e5-9203-0f5ff5c37b45.jpg)

**Comment by crumdidlyumshis** [comment]
![wowscrnshot_101815_152538](https://cloud.githubusercontent.com/assets/7307335/10593650/1a46f21e-768b-11e5-8c82-493965b145c9.jpg)

**Comment by Bunny67** [comment]
![wowscrnshot_102015_181959](https://cloud.githubusercontent.com/assets/5816685/10611975/6d473eb6-7757-11e5-88d9-d96eaf9a73e6.jpg)
There is an option

**Comment by crumdidlyumshis** [comment]
Is it possible to add a conditional script? If Skada is shown, hide chat, else, show chat.

**Comment by Bunny67** [comment]
I think this method will lead to other bugs :(

**Comment by crumdidlyumshis** [comment]
Okie dokie, your the man with the plan! :)

**Comment by Bunny67** [comment]
It will be implemented in another addon
