### ISSUE TITLE
Shaman weapon buffs

### ISSUE THREAD

**Issue by Dean1989** [ElvUI/ElvUI#70]
hello, first of all ty for your work, is amazing.
I didn't found an option to diplay the shaman weapon buffs, like flametongue, in the upper corner of the screen near the minimap, is possible do it? ty

**Comment by Bunny67** [comment]
How long ago I tried to implement, but it did not work :( How will free time to think about them

Ru: Как то давно пробывал реализовать, но ничего не получилось :( Как будет свободное время подумаю над ними

**Comment by Dean1989** [comment]
thank you :)
