### ISSUE TITLE
Loot/Trade Config - Global Channels

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#74]
![wowscrnshot_101615_185827 - copy](https://cloud.githubusercontent.com/assets/7307335/10593598/b74620e0-768a-11e5-96dc-968a1b88cca7.jpg)
![wowscrnshot_101615_185827](https://cloud.githubusercontent.com/assets/7307335/10593602/b8e9d45a-768a-11e5-932a-d8a3b1abfebf.jpg)

**Comment by Bunny67** [comment]
fix, will add in the next update
