### ISSUE TITLE
REP Bar Tooltip - Mouseover

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#75]
The tooltip is stuck to the bottom whereas the exp bar is positioned on the mouse cursor.

![wowscrnshot_101615_204906](https://cloud.githubusercontent.com/assets/7307335/10593614/cf94e9ba-768a-11e5-8b25-d1ded08105b2.jpg)

**Comment by Bunny67** [comment]
fix, will add in the next update
