### ISSUE TITLE
[suggestion] fast mana/energy regen update

### ISSUE THREAD

**Issue by Dean1989** [ElvUI/ElvUI#79]
hello bunny,
this is a suggestion i found on warmane forum to make mana/energy update more fast, is very useful for feral/rogue players that need to know exactly how many energy they have, i report it to you if you want to add it in your next release:
Open the following file: ElvUI\modules\unitframes\units\player.lua
Add this below line 14: frame.Power.frequentUpdates = true;
Then, open: ElvUI\modules\unitframes\elements\power.lua
and add this bellowing line 26: power.value.frequentUpdates = true;
Open: ElvUI\libs\oUF\elements\tags.lua
and change line 602 into: timer = .1

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI/blob/master/ElvUI/modules/unitframes/units/player.lua#L16

the rest is added

**Comment by crumdidlyumshis** [comment]
I don't think this is working for Party Frames afaik.

**Comment by Bunny67** [comment]
Player and Target Frames only
