### ISSUE TITLE
Raid Indicators

### ISSUE THREAD

**Issue by lierox90** [ElvUI/ElvUI#8]
They seem jsut to not work, they dont refresh when spell is cast. also there is missing role icon for 5mans also idk if its possible but it would be really nice if i could filter spells not by exacly given spell but by spell type ex poison or magic

**Comment by lierox90** [comment]
i found you issue here, wrong spell ids for ex you have writen into code ide 48440 which is Rejuvenation Rank 14 however max for lvl 80 is rank 15 and addon doesnt detect change

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI/commit/aaa89c3dc9d9e3bd6903988770fb8e96a92b0aec fix?

**Comment by lierox90** [comment]
Yes works perfectly now :+1:
