### ISSUE TITLE
DataTexts - Speed

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#80]
Doesn't seem to work.

![wowscrnshot_102015_234718](https://cloud.githubusercontent.com/assets/7307335/10713982/8c6cee14-7aa2-11e5-9eae-d32983885a7c.jpg)

**Comment by Bunny67** [comment]
I should work on any class of checks?

Ru: Должен работать, на каком классе проверял?

**Comment by Bunny67** [comment]
Still relevant?

**Comment by crumdidlyumshis** [comment]
I think it works now. However, I have not had any gear with haste on it. So I cannot verify. The tooltip works though! :)

**Comment by Bunny67** [comment]
Up to date?

**Comment by crumdidlyumshis** [comment]
Yes, sorry!
