### ISSUE TITLE
Capture bar - Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#82]
![wowscrnshot_110415_004202](https://cloud.githubusercontent.com/assets/7307335/10958993/50f65db2-8339-11e5-9211-5cbf7e02e252.jpg)

**Comment by Bunny67** [comment]
So it should be :(

**Comment by crumdidlyumshis** [comment]
You sure it can't be skinned? http://git.tukui.org/Azilroka/addonskins/blob/master/Skins/Blizzard/WorldStateCaptureBar.lua

**Comment by Bunny67** [comment]
Maybe I add AddOnSkins, but there is little time :(
In ElvUI add will not :(

Ru: Возможно добавлю AddOnSkins, но пока мало времени :(
В ElvUI добавлять не буду :(

**Comment by crumdidlyumshis** [comment]
Okay thank you!
