### ISSUE TITLE
Capture bar - Switching forms

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#83]
When switching forms as a druid, the capture bar moves to the right of the screen under the mini-map.

BEFORE

![wowscrnshot_110415_211646](https://cloud.githubusercontent.com/assets/7307335/10959025/8ad3dea6-8339-11e5-9c22-6313786a2a01.jpg)

AFTER

![wowscrnshot_110415_211648](https://cloud.githubusercontent.com/assets/7307335/10959028/90e9546a-8339-11e5-8c70-7003a24dd278.jpg)

**Comment by Bunny67** [comment]
amended, check
