### ISSUE TITLE
Login - Name Color

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#85]
Not sure if this is a bug, but when logging in, the names are not colored.

![wowscrnshot_110215_172402](https://cloud.githubusercontent.com/assets/7307335/11128834/e129d180-8941-11e5-8bb7-c3065e9b6363.jpg)

**Comment by Bunny67** [comment]
It must be corrected

**Comment by crumdidlyumshis** [comment]
Am I doing something wrong? Do I need to check something?

![wowscrnshot_111315_185052](https://cloud.githubusercontent.com/assets/7307335/11160961/aaee6f62-8a37-11e5-9877-0e9346372342.jpg)

**Comment by Bunny67** [comment]
If a character is offline his nickname color will not

Ru: Если персонаж оффлайн его ник цветным не станет

**Comment by crumdidlyumshis** [comment]
I saw it working last night! However, its slightly buggy. Sometimes it shows them colored, and sometimes it doesn't, even with the same person. 

I think you can close this. :)
