### ISSUE TITLE
Pet happines Indicator

### ISSUE THREAD

**Issue by lierox90** [ElvUI/ElvUI#9]
Its missing, there is no way to check pets happines when using elvui

**Comment by Bunny67** [comment]
use tag "happiness" for player

**Comment by lierox90** [comment]
could you elaborate this ? where should i use it and how should i use it

**Comment by Bunny67** [comment]
UnitFrames -> Player -> Custom Texts -> Select Yor Custom Text -> Text Format = [happiness]

I hope it is clear.
Google translete

**Comment by lierox90** [comment]
Yeah awesome, it work, thanks :) :+1:
