### ISSUE TITLE
Class Action Bar - Enhancement

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#95]
Would it be possible to add more class action bars to ElvUI. Currently the druid, palidan, and others have class bars. However, could you add it for Hunters? Aspect of Cheeta, Aspect of Pack, Aspect of Viper.. etc...

![screenshot10193s](https://cloud.githubusercontent.com/assets/7307335/11414631/525429e8-93bd-11e5-85fa-d833dc1d1472.jpg)
![screenshot10193](https://cloud.githubusercontent.com/assets/7307335/11414633/543dd1f0-93bd-11e5-8ab6-f180336ae7f8.jpg)

**Comment by crumdidlyumshis** [comment]
Or maybe skin http://www.curse.com/addons/wow/flo-aspect-bar? ElvUI_AddOnSkins

**Comment by Bunny67** [comment]
Added to ElvUI_AddOnSkins
