### ISSUE TITLE
Hyperlink compare is broken.

### ISSUE THREAD

**Issue by Kkthnx** [ElvUI/ElvUI#96]
![wowscrnshot_112615_233555](https://cloud.githubusercontent.com/assets/1692977/11434255/7e8486e0-9497-11e5-9b6b-e9a71a16d2f2.jpg)
![wowscrnshot_112615_234234](https://cloud.githubusercontent.com/assets/1692977/11434256/7e855f02-9497-11e5-9bf0-8f50cc958ed0.jpg)

As you can see when you hover over something the compare tip doesnt work and neither does the spell one.

**Comment by lbjdaking23** [comment]
Seems to be work fine on my end. Possibly a settings issue or addon confliction?

**Comment by Kkthnx** [comment]
I'll double check. Will report back. Thanks for letting me know it could be on my end.

**Comment by Kkthnx** [comment]
Yup! The addon ChatConsolidate messes up the hyperlink deal. Sorry for not looking into this better before reporting. Thanks @lbjdaking23
