### ISSUE TITLE
Aura Bars - Attach To Player Frame Aura Bars not working correctly

### ISSUE THREAD

**Issue by SmoothRossi** [ElvUI/ElvUI#97]
![wowscrnshot_120215_162557](https://cloud.githubusercontent.com/assets/16121307/11536854/3015a87a-9912-11e5-8e87-f55dcfcc1b38.jpg)

Please see the above screenshot. Previously, with the above configuration, the Aura Bars of Target would appear above the player frame (Green Box) rather than the target frame (red box).

**Comment by Bunny67** [comment]
fix
