### ISSUE TITLE
Pet target breaking party frame. 

### ISSUE THREAD

**Issue by ThermalX** [ElvUI/ElvUI#98]
On my hunter, upon enabling the pet target frame the party frame stops working and gives me these lua errors:

Message: ...\AddOns\ElvUI\modules\unitframes\units\pettarget.lua:324: bad argument #1 to 'pairs' (table expected, got nil)
Time: 12/02/15 20:39:55
Count: 1
Stack: ...ade\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...ade\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ade\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...face\AddOns\ElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...face\AddOns\ElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: self = <table> {
 GetTimeInfo = <function> defined @Interface\AddOns\ElvUI\core\math.lua:260
 privateVars = <table> {
 }
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\ElvUI\libs\AceTimer-3.0\AceTimer-3.0.lua:311
 FormatMoney = <function> defined @Interface\AddOns\ElvUI\core\math.lua:286
 StaticPopup_EscapePressed = <function> defined @Interface\AddOns\ElvUI\core\staticpopups.lua:319
 CopyTable = <function> defined @Interface\AddOns\ElvUI\core\core.lua:368
 SetMoversPositions = <function> defined @Interface\AddOns\ElvUI\core\movers.lua:394
 ScheduleTimer = <function> defined @Interface\AddOns\ElvUI\libs\AceTimer-3.0\AceTimer-3.0.lua:276
 PriestColors = <table> {
 }
 RegisterModule = <function> defined @Interface\AddOns\ElvUI\core\core.lua:279
 SetupTheme = <function> defined @Interface\AddOns\ElvUI\core\install.lua:202
 media = <table> {
 }
 SetUpAnimGroup = <function> defined @Interface\AddOns\ElvUI\core\animation.lua:6
 data = <table> {
 }
 Role = "Melee"
 UIScale = <function> defined @Interface\AddOns\ElvUI\core\pixelperfect.lua:12
 db = <table> {
 }
 ToggleConfigMode = <function> defined @Interface\AddOns\ElvUI\core\config.lua:54
 SetEnabledState = <function> defined @Interface\AddOns\ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:274
 Options = <table> {
 }
 Layout = <table> {
 }
 tDeleteItem = <function> defined @Interface\AddOns\ElvUI\core\animation.lua:280
 LoadCommands = <function> defined @Interface\AddOns\ElvUI\core\commands.lua:171
 HiddenFrame = <unnamed> {
 }
 DisableAddon = <function> defined @Interface\AddOns\ElvUI\core\commands.lua:28
 NewModule = <function> defined @Interface\AddOns\ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 UIFrameFade = <function> defined @Interface\AddOns\ElvUI\core\animation.lua:216
 MinimapWidth = 176
 StaticPopup_IsLastDisplayedFrame = <function> defined @Interface\AddOns\ElvUI\core\staticpopups.lua:380
 EndAprilFoolsDay2014 = <function> defined @Interface\AddOns\ElvUI\core\core.lua:797
 UpdateBackdropColors = <function> defined @Interface\AddOns\ElvUI\core\core.lua:220
 StaticPopup_OnHide = <function> defined @Interface\AddOns\ElvUI\core\staticpopups.lua:420
 name = "ElvUI"
 WorldMap = <table> {
 }
 StopMassiveShake = <function> defined @Interface\AddOns\ElvUI\core\core.lua:568
 Disable = <function> defined @Interface\AddOns\ElvUI\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 TimeColors = <table> {
 }
 SlideOut = <function> defined @Interface\AddOns\ElvUI\core\animation.lua:161
 Unhook = <function> defined @Interface\AddOns\ElvUI\libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Interface\AddOns\ElvUI\core\core.lua:88
 Install = <function> defined @Interface\AddOns\ElvUI\core\install.lua:812
 RegisterCooldown = <function> defined @Interface\AddOns\ElvUI\core\cooldowns.lua:126
 TimeFormats = <table> {
 }
 RGBToHex = <function> defined @Interface\AddOns\ElvUI\core\math.lua:52
 StaticPopup_Resize = <function> defined @Interface\AddOns\ElvUI\core\staticpopups.lua:557
 Cooldown_StopTimer = <function> defined @Interface\AddOns\ElvUI\core\cooldowns.lua:73
 BeginFoolsDayEvent = <function> defined @Interface\AddOns\ElvUI\core\core.lua:605
 UpdateNudgeFrame = <function> defined @Interface\AddOns\ElvUI\core\config.lua:

--------------------------------------------------------------

Message: Interface\AddOns\ElvUI_Config\unitframes.lua:3385: attempt to index field 'ElvUF_Party' (a nil value)
Time: 12/02/15 20:40:02
Count: 1
Stack: (tail call): ?
Interface\AddOns\ElvUI_Config\unitframes.lua:3385: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1396: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1588: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1513: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1493>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...e\AddOns\ElvUI_Config\libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:506: in function `SetSelected'
...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:192: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:188>

Locals: (*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1

--------------------------------------------------------------

Message: ...\AddOns\ElvUI\modules\unitframes\units\pettarget.lua:324: bad argument #1 to 'pairs' (table expected, got nil)
Time: 12/02/15 20:41:15
Count: 1
Stack: (tail call): ?
[C]: ?
...\AddOns\ElvUI\modules\unitframes\units\pettarget.lua:324: in function `?'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:826: in function `Update'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:831: in function `CreateAndUpdateUF'
Interface\AddOns\ElvUI_Config\unitframes.lua:3048: in function <Interface\AddOns\ElvUI_Config\unitframes.lua:3048>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...e\AddOns\ElvUI_Config\libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...ig\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68: in function <...ig\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

Locals: (*temporary) = "LeftButton"
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1

--------------------------------------------------------------

Message: ...\AddOns\ElvUI\modules\unitframes\units\pettarget.lua:324: bad argument #1 to 'pairs' (table expected, got nil)
Time: 12/02/15 20:41:22
Count: 1
Stack: (tail call): ?
[C]: ?
...\AddOns\ElvUI\modules\unitframes\units\pettarget.lua:324: in function `?'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:826: in function `Update'
...rface\AddOns\ElvUI\modules\unitframes\unitframes.lua:831: in function `CreateAndUpdateUF'
Interface\AddOns\ElvUI_Config\unitframes.lua:2987: in function <Interface\AddOns\ElvUI_Config\unitframes.lua:2987>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...e\AddOns\ElvUI_Config\libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...ig\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68: in function <...ig\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

Locals: (*temporary) = "LeftButton"
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1

Everything I did to try and fix it only made it worse.

**Comment by ThermalX** [comment]
This is the error i get in the party frame:

Message: Interface\AddOns\ElvUI_Config\unitframes.lua:3385: attempt to index field 'ElvUF_Party' (a nil value)
Time: 12/02/15 21:01:33
Count: 1
Stack: (tail call): ?
Interface\AddOns\ElvUI_Config\unitframes.lua:3385: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1396: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1588: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1513: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1493>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...e\AddOns\ElvUI_Config\libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:506: in function `SetSelected'
...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:192: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:188>

Locals: (*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1

**Comment by Bunny67** [comment]
fixed

**Comment by ThermalX** [comment]
thank you very much =)
